services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: BROADCAST_DRIVER
        value: pusher
      - key: PUSHER_APP_ID
        value: local
      - key: PUSHER_APP_KEY
        value: local
      - key: PUSHER_APP_SECRET
        value: local
      - key: PUSHER_APP_CLUSTER
        value: mt1
      - key: PUSHER_HOST
        value: sjp-php-p2-phuong-luan.onrender.com
      - key: PUSHER_PORT
        value: 443