services:
  - type: web
    name: laravel-app
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://sjp-php-p2-phuong-luan.onrender.com
      - key: PORT
        value: 80
